name: Publish to npm
on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn ci
      - run: yarn test
      - run: yarn build
      - run: |
          echo "npmAuthToken: \"${{ secrets.GITHUB_TOKEN }}\"" >> .npmrc
      - run: npm publish --access=public
